package xta.game.creature.body

import xta.flash.CocId
import xta.flash.CocIdLookup

enum class WingType(override val cocID: Int): CocId {
	NONE(0),
	BEE_SMALL(1),
	BEE_LARGE(2),
	HARPY(4),
	IMP(5),
	BAT_LIKE_TINY(6),
	BAT_LIKE_LARGE(7),
	SHARK_FIN(8),
	FEATHERED_LARGE(9),
	DRACONIC_SMALL(10),
	DRACONIC_LARGE(11),
	GIANT_DRAGONFLY(12),
	BAT_LIKE_LARGE_2(13),
	DRACONIC_HUGE(14),
	FEATHERED_PHOENIX(15),
	FEATHERED_ALICORN(16),
	MANTIS_SMALL(17),
	MANTIS_LARGE(18),
	MANTIS_LARGE_2(19),
	GARGOYLE_LIKE_LARGE(20),
	PLANT(21),
	MANTICORE_SMALL(22),
	MANTICORE_LARGE(23),
	BAT_ARM(24),
	VAMPIRE(25),
	FEY_DRAGON(26),
	FEATHERED_AVIAN(27),
	NIGHTMARE(28),
	FEATHERED_SPHINX(29),
	ETHEREAL(30),
	THUNDEROUS_AURA(31),
	LEVITATION(32),
	DEVILFEATHER(33),
	FAIRY(34),
	WINDY_AURA(35),
	SEA_DRAGON(36),
	;
	companion object: CocIdLookup<WingType>(values())
}
